### Student Information
Name:陳權仁

Student ID:112062676

GitHub ID:jack861225

Kaggle name:Chuan-Jen Chen

Kaggle private scoreboard snapshot:

[Snapshot](img/pic0.png)

---

### Instructions

1. First: __This part is worth 30% of your grade.__ Do the **take home** exercises in the DM2023-Lab2-master. You may need to copy some cells from the Lab notebook to this notebook. 


2. Second: __This part is worth 30% of your grade.__ Participate in the in-class [Kaggle Competition](https://www.kaggle.com/t/09b1d0f3f8584d06848252277cb535f2) regarding Emotion Recognition on Twitter by this link https://www.kaggle.com/t/09b1d0f3f8584d06848252277cb535f2. The scoring will be given according to your place in the Private Leaderboard ranking: 
    - **Bottom 40%**: Get 20% of the 30% available for this section.

    - **Top 41% - 100%**: Get (60-x)/6 + 20 points, where x is your ranking in the leaderboard (ie. If you rank 3rd your score will be (60-3)/6 + 20 = 29.5% out of 30%)   
    Submit your last submission __BEFORE the deadline (Dec. 27th 11:59 pm, Wednesday)_. Make sure to take a screenshot of your position at the end of the competition and store it as '''pic0.png''' under the **img** folder of this repository and rerun the cell **Student Information**.
    

3. Third: __This part is worth 30% of your grade.__ A report of your work developping the model for the competition (You can use code and comment it). This report should include what your preprocessing steps, the feature engineering steps and an explanation of your model. You can also mention different things you tried and insights you gained. 


4. Fourth: __This part is worth 10% of your grade.__ It's hard for us to follow if your code is messy :'(, so please **tidy up your notebook** and **add minimal comments where needed**.


Upload your files to your repository then submit the link to it on the corresponding e-learn assignment.

Make sure to commit and save your changes to your repository __BEFORE the deadline (Dec. 31th 11:59 pm, Sunday)__. 

In [1]:
### Begin Assignment Here
# dm2023-isa5810-lab2-homework/tweets_DM.json
import pandas as pd
import json

# 讀取json檔案中的每行json格式
with open('dm2023-isa5810-lab2-homework/tweets_DM.json', 'r', encoding='utf-8') as file:
    json_list = [json.loads(line) for line in file]

df = pd.DataFrame(json_list)

In [2]:
# 提取tweet_id跟text
def extract_tweet_id(row):
    if '_source' in row and 'tweet' in row['_source'] and 'tweet_id' in row['_source']['tweet']:
        return row['_source']['tweet']['tweet_id']
    else:
        return None

def extract_text(row):
    if '_source' in row and 'tweet' in row['_source'] and 'text' in row['_source']['tweet']:
        return row['_source']['tweet']['text']
    else:
        return None

df['tweet_id'] = df.apply(extract_tweet_id, axis=1)  # 提取tweet_id成新的行
df['text'] = df.apply(extract_text, axis=1)  # 提取text成新的行

print(df[['tweet_id', 'text']])

         tweet_id                                               text
0        0x376b20  People who post "add me on #Snapchat" must be ...
1        0x2d5350  @brianklaas As we see, Trump is dangerous to #...
2        0x28b412  Confident of your obedience, I write to you, k...
3        0x1cd5b0                Now ISSA is stalking Tasha 😂😂😂 <LH>
4        0x2de201  "Trust is not the same as faith. A friend is s...
...           ...                                                ...
1867530  0x316b80  When you buy the last 2 tickets remaining for ...
1867531  0x29d0cb  I swear all this hard work gone pay off one da...
1867532  0x2a6a4f  @Parcel2Go no card left when I wasn't in so I ...
1867533  0x24faed  Ah, corporate life, where you can date <LH> us...
1867534  0x34be8c             Blessed to be living #Sundayvibes <LH>

[1867535 rows x 2 columns]


In [3]:
data = df[['tweet_id', 'text']]  #將tweet_id跟text獨自放到data中
data

tweet_id                                               text
0        0x376b20  People who post "add me on #Snapchat" must be ...
1        0x2d5350  @brianklaas As we see, Trump is dangerous to #...
2        0x28b412  Confident of your obedience, I write to you, k...
3        0x1cd5b0                Now ISSA is stalking Tasha 😂😂😂 <LH>
4        0x2de201  "Trust is not the same as faith. A friend is s...
...           ...                                                ...
1867530  0x316b80  When you buy the last 2 tickets remaining for ...
1867531  0x29d0cb  I swear all this hard work gone pay off one da...
1867532  0x2a6a4f  @Parcel2Go no card left when I wasn't in so I ...
1867533  0x24faed  Ah, corporate life, where you can date <LH> us...
1867534  0x34be8c             Blessed to be living #Sundayvibes <LH>

[1867535 rows x 2 columns]

In [4]:
data_emotion = pd.read_csv("dm2023-isa5810-lab2-homework/emotion.csv") #讀取emotion檔案
data_emotion

tweet_id       emotion
0        0x3140b1       sadness
1        0x368b73       disgust
2        0x296183  anticipation
3        0x2bd6e1           joy
4        0x2ee1dd  anticipation
...           ...           ...
1455558  0x38dba0           joy
1455559  0x300ea2           joy
1455560  0x360b99          fear
1455561  0x22eecf           joy
1455562  0x2fb282  anticipation

[1455563 rows x 2 columns]

In [5]:
data_identification = pd.read_csv("dm2023-isa5810-lab2-homework/data_identification.csv") #讀取data_identification檔案
data_identification

tweet_id identification
0        0x28cc61           test
1        0x29e452          train
2        0x2b3819          train
3        0x2db41f           test
4        0x2a2acc          train
...           ...            ...
1867530  0x227e25          train
1867531  0x293813          train
1867532  0x1e1a7e          train
1867533  0x2156a5          train
1867534  0x2bb9d2          train

[1867535 rows x 2 columns]

In [6]:
merge_text_identification = pd.merge(data, data_identification, on='tweet_id', how='inner') #將identication merge到data中
merge_text_identification

tweet_id                                               text  \
0        0x376b20  People who post "add me on #Snapchat" must be ...   
1        0x2d5350  @brianklaas As we see, Trump is dangerous to #...   
2        0x28b412  Confident of your obedience, I write to you, k...   
3        0x1cd5b0                Now ISSA is stalking Tasha 😂😂😂 <LH>   
4        0x2de201  "Trust is not the same as faith. A friend is s...   
...           ...                                                ...   
1867530  0x316b80  When you buy the last 2 tickets remaining for ...   
1867531  0x29d0cb  I swear all this hard work gone pay off one da...   
1867532  0x2a6a4f  @Parcel2Go no card left when I wasn't in so I ...   
1867533  0x24faed  Ah, corporate life, where you can date <LH> us...   
1867534  0x34be8c             Blessed to be living #Sundayvibes <LH>   

        identification  
0                train  
1                train  
2                 test  
3                train  
4                 test  
...                ...  
1867530           test  
1867531           test  
1867532           test  
1867533          train  
1867534          train  

[1867535 rows x 3 columns]

In [7]:
#用identifcation中的值將data分成training用的跟testing用的
train_df = merge_text_identification[merge_text_identification['identification'] == 'train']
test_df = merge_text_identification[merge_text_identification['identification'] == 'test']

test_df

tweet_id                                               text  \
2        0x28b412  Confident of your obedience, I write to you, k...   
4        0x2de201  "Trust is not the same as faith. A friend is s...   
9        0x218443  When do you have enough ? When are you satisfi...   
30       0x2939d5  God woke you up, now chase the day #GodsPlan #...   
33       0x26289a  In these tough times, who do YOU turn to as yo...   
...           ...                                                ...   
1867525  0x2913b4  "For this is the message that ye heard from th...   
1867529  0x2a980e  "There is a lad here, which hath five barley l...   
1867530  0x316b80  When you buy the last 2 tickets remaining for ...   
1867531  0x29d0cb  I swear all this hard work gone pay off one da...   
1867532  0x2a6a4f  @Parcel2Go no card left when I wasn't in so I ...   

        identification  
2                 test  
4                 test  
9                 test  
30                test  
33                test  
...                ...  
1867525           test  
1867529           test  
1867530           test  
1867531           test  
1867532           test  

[411972 rows x 3 columns]

In [8]:
train_df = pd.merge(train_df, data_emotion, on='tweet_id', how='inner') #再將emotion透過tweet_id merge到training data中
train_df

tweet_id                                               text  \
0        0x376b20  People who post "add me on #Snapchat" must be ...   
1        0x2d5350  @brianklaas As we see, Trump is dangerous to #...   
2        0x1cd5b0                Now ISSA is stalking Tasha 😂😂😂 <LH>   
3        0x1d755c  @RISKshow @TheKevinAllison Thx for the BEST TI...   
4        0x2c91a8       Still waiting on those supplies Liscus. <LH>   
...           ...                                                ...   
1455558  0x321566  I'm SO HAPPY!!! #NoWonder the name of this sho...   
1455559  0x38959e  In every circumtance I'd like to be thankful t...   
1455560  0x2cbca6  there's currently two girls walking around the...   
1455561  0x24faed  Ah, corporate life, where you can date <LH> us...   
1455562  0x34be8c             Blessed to be living #Sundayvibes <LH>   

        identification       emotion  
0                train  anticipation  
1                train       sadness  
2                train          fear  
3                train           joy  
4                train  anticipation  
...                ...           ...  
1455558          train           joy  
1455559          train           joy  
1455560          train           joy  
1455561          train           joy  
1455562          train           joy  

[1455563 rows x 4 columns]

In [9]:
import pandas as pd

## 存成pickle file
train_df.to_pickle("train_df.pkl") 
test_df.to_pickle("test_df.pkl")

In [10]:
## 讀取pickle file
train_df = pd.read_pickle("train_df.pkl")
test_df = pd.read_pickle("test_df.pkl")

# 使用BOW處理data

In [11]:
#利用BOW處理data

from sklearn.feature_extraction.text import CountVectorizer

BOW_vectorizer = CountVectorizer() 

# 1. Learn a vocabulary dictionary of all tokens in the raw documents.
BOW_vectorizer.fit(train_df['text'])

# 2. Transform documents to document-term matrix.
train_data_BOW_features = BOW_vectorizer.transform(train_df['text'])
test_data_BOW_features = BOW_vectorizer.transform(test_df['text'])

# check the result
train_data_BOW_features

<1455563x794247 sparse matrix of type '<class 'numpy.int64'>'
	with 18849355 stored elements in Compressed Sparse Row format>

In [32]:
#取出前1000最常出現的term

import nltk

# build analyzers (bag-of-words)
BOW_1000 = CountVectorizer(max_features=1000, tokenizer=nltk.word_tokenize) 

# apply analyzer to training data
BOW_1000.fit(train_df['text'])

train_data_BOW_features_1000 = BOW_1000.transform(train_df['text'])

## check dimension
train_data_BOW_features_1000.shape

C:\Users\陳權仁\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\feature_extraction\text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


(1455563, 1000)

# 使用Decision Tree建Model預測(同Lab2)

In [36]:
from sklearn.tree import DecisionTreeClassifier

# 跟lab2一樣將training data的text跟label存成X_train跟y_train
X_train = BOW_1000.transform(train_df['text'])
y_train = train_df['emotion']


# 跟lab2一樣將test data的text存成X_test
X_test = BOW_1000.transform(test_df['text'])

print('X_train.shape: ', X_train.shape)
print('y_train.shape: ', y_train.shape)
print('X_test.shape: ', X_test.shape)

X_train.shape:  (1455563, 1000)
y_train.shape:  (1455563,)
X_test.shape:  (411972, 1000)


In [14]:
## 跟lab2一樣build DecisionTree model
DT_model = DecisionTreeClassifier(random_state=1)

## training
DT_model = DT_model.fit(X_train, y_train)

## predict
y_train_pred = DT_model.predict(X_train)
y_test_pred = DT_model.predict(X_test)

y_test_pred[:10]

array(['anticipation', 'trust', 'joy', 'anticipation', 'trust',
       'surprise', 'sadness', 'anger', 'joy', 'anticipation'],
      dtype=object)

In [15]:
## 查看training data的accuracy

from sklearn.metrics import accuracy_score

acc_train = accuracy_score(y_true=y_train, y_pred=y_train_pred)

print('training accuracy: {}'.format(round(acc_train, 2)))


training accuracy: 0.97


In [16]:
#將test data中的tweet_id提出來存成csv檔要做為最終答案用

answer_tweet_id = pd.DataFrame(test_df[['tweet_id']])
answer_tweet_id = answer_tweet_id.rename(columns={'tweet_id': 'id'}) #將tweet_id rename成id

#answer_tweet_id.to_csv('G:\我的雲端硬碟\研究所\清大\碩一上\資料探勘與應用\DMLab2\DM2023-Lab2-Master\Homework\id.csv', index=False)
answer_tweet_id.to_csv('id.csv', index=False)



# answer = test_df[['tweet_id']]
#answer = answer_tweet_id.append(answer_emotion, ignore_index=True)
#answer_tweet_id = pd.concat([answer_tweet_id, answer_emotion], ignore_index=True)
#result = pd.concat([answer_tweet_id, answer_emotion], axis=1)
#result

In [17]:
dff = pd.read_csv('id.csv')

# 將預測的emotion加到answer檔案中
answer_emotion = pd.DataFrame({'emotion' : y_test_pred})
dff = pd.concat([dff, answer_emotion], axis=1)
dff

# 再寫成csv檔
dff.to_csv('answer.csv', index=False)

# Deep Learning方式:

In [37]:
## deal with label (string -> one-hot)
import keras
from sklearn.preprocessing import LabelEncoder
import numpy as np

y_train = train_df['emotion']
label_encoder = LabelEncoder()
label_encoder.fit(y_train)

def label_encode(le, labels):
    enc = le.transform(labels)
    return keras.utils.to_categorical(enc)

def label_decode(le, one_hot_label):
    dec = np.argmax(one_hot_label, axis=1)
    return le.inverse_transform(dec)

y_train = label_encode(label_encoder, y_train)



check label:  ['anger' 'anticipation' 'disgust' 'fear' 'joy' 'sadness' 'surprise'
 'trust']

## Before convert
y_train[0:4]:
 0    anticipation
1         sadness
2            fear
3             joy
4    anticipation
5             joy
6         sadness
7    anticipation
Name: emotion, dtype: object

y_train.shape:  (1455563,)


## After convert
y_train[0:4]:
 [[0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]]

y_train.shape:  (1455563, 8)


In [38]:
# I/O check
input_shape = X_train.shape[1]
print('input_shape: ', input_shape)

output_shape = len(label_encoder.classes_)
print('output_shape: ', output_shape)

input_shape:  1000
output_shape:  8


In [39]:
from keras.models import Model
from keras.layers import Input, Dense
from keras.layers import ReLU, Softmax

# input layer
model_input = Input(shape=(input_shape, ))  # 1000
X = model_input

# 1st hidden layer
X_W1 = Dense(units=64)(X)  # 64
H1 = ReLU()(X_W1)

# 2nd hidden layer
H1_W2 = Dense(units=64)(H1)  # 64
H2 = ReLU()(H1_W2)

# output layer
H2_W3 = Dense(units=output_shape)(H2)  # 4
H3 = Softmax()(H2_W3)

model_output = H3

# create model
model = Model(inputs=[model_input], outputs=[model_output])

# loss function & optimizer
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# show model construction
model.summary()

Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_4 (InputLayer)        [(None, 1000)]            0         
                                                                 
 dense_9 (Dense)             (None, 64)                64064     
                                                                 
 re_lu_6 (ReLU)              (None, 64)                0         
                                                                 
 dense_10 (Dense)            (None, 64)                4160      
                                                                 
 re_lu_7 (ReLU)              (None, 64)                0         
                                                                 
 dense_11 (Dense)            (None, 8)                 520       
                                                                 
 softmax_3 (Softmax)         (None, 8)                 0   

In [40]:
from keras.callbacks import CSVLogger

# training setting
epochs = 8
batch_size = 32

# training
history = model.fit(X_train, y_train, 
                    epochs=epochs, 
                    batch_size=batch_size)
print('training finish')

Epoch 1/8
45487/45487 [==============================] - 59s 1ms/step - loss: 1.3539 - accuracy: 0.5074
Epoch 2/8
45487/45487 [==============================] - 54s 1ms/step - loss: 1.3078 - accuracy: 0.5233
Epoch 3/8
45487/45487 [==============================] - 55s 1ms/step - loss: 1.2944 - accuracy: 0.5284
Epoch 4/8
45487/45487 [==============================] - 54s 1ms/step - loss: 1.2870 - accuracy: 0.5313
Epoch 5/8
45487/45487 [==============================] - 53s 1ms/step - loss: 1.2817 - accuracy: 0.5333
Epoch 6/8
45487/45487 [==============================] - 53s 1ms/step - loss: 1.2780 - accuracy: 0.5347
Epoch 7/8
45487/45487 [==============================] - 53s 1ms/step - loss: 1.2750 - accuracy: 0.5358
Epoch 8/8
45487/45487 [==============================] - 54s 1ms/step - loss: 1.2728 - accuracy: 0.5369
training finish


In [41]:
## predict
pred_result = model.predict(X_test, batch_size=128)
pred_result[:5]

3219/3219 [==============================] - 4s 1ms/step


array([[2.88413395e-03, 5.88342547e-01, 5.19837625e-03, 1.13964528e-02,
        2.46198952e-01, 1.26568759e-02, 3.94857721e-03, 1.29374176e-01],
       [3.84808736e-05, 4.53697950e-01, 2.17304369e-05, 8.77727382e-03,
        3.96583602e-02, 5.47846139e-04, 1.11574824e-04, 4.97146755e-01],
       [1.16036996e-01, 1.27871975e-01, 2.51648635e-01, 1.35582834e-02,
        1.87332228e-01, 2.56718725e-01, 1.47445751e-02, 3.20885703e-02],
       [1.23502808e-02, 1.61249116e-01, 1.59435086e-02, 1.06027294e-02,
        5.32367706e-01, 3.01346835e-02, 1.08020119e-02, 2.26550043e-01],
       [6.51201559e-03, 5.72244465e-01, 2.23414395e-02, 1.67849325e-02,
        1.45263255e-01, 2.94696838e-02, 1.19958287e-02, 1.95388392e-01]],
      dtype=float32)

In [42]:
pred_result = label_decode(label_encoder, pred_result)
pred_result[:5]

array(['anticipation', 'trust', 'sadness', 'joy', 'anticipation'],
      dtype=object)

In [43]:
dff = pd.read_csv('id.csv')

# 將預測的emotion加到answer檔案中
answer_emotion = pd.DataFrame({'emotion' : pred_result})
dff = pd.concat([dff, answer_emotion], axis=1)
dff

# 再寫成csv檔
dff.to_csv('answer.csv', index=False)